spring:
  application:
    name: product-service
  profiles:
    active: ${PROFILE_ACTIVE:LOCAL}
  jpa:
    hibernate:
#      ddl-auto: update
#    generate-ddl: true
    show-sql: false
  flyway:
    enabled: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:user}
    password: ${SPRING_RABBITMQ_PASSWORD:0d76739a-a5ec-4ee2-a847-56081ce6a6c9}

server:
  port: ${SERVER_PORT:8093}
  servlet:
    context-path: /product-service

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    enable:
      jvm: true
    distribution:
      slo.http.server.requests: 50ms, 100ms, 200ms, 300ms, 500ms, 1s
    tags:
      application: product-service

jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH}