spring-datasource:
  url: jdbc:postgresql://localhost:5435/product_service_db?serverTimezone=UTC
  username: product_service_user@2025!#
  password: 6fbed52a-ea56-4a64-a66e-c34c754a42a2
  driverClassName: org.postgresql.Driver
  maximumPoolSize: 5
  minimumIdle: 5
  idleTimeout: 30000