services:

  invoice-service-db:
    image: postgres
    container_name: invoice-service-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=invoice_service_user@2025!#
      - POSTGRES_PASSWORD=6fbed52a-ea56-4a64-a66e-c34c754a42a2
      - POSTGRES_DB=invoice_service_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5437:5432"
    networks:
      - local_ecommerce-services
    volumes:
      - invoice_service_db_data:/var/lib/postgresql/data

  invoice-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice-service
    restart: unless-stopped
    env_file:
      - invoice-service.env
    ports:
      - "8095:8095"
    volumes:
      - "C:/Users/luan.paiva/Documents/Projeto ADA/public_key.pem:/app/keys/public_key.pem:ro"
    networks:
      - local_ecommerce-services
    depends_on:
      - invoice-service-db

networks:
  local_ecommerce-services:
    external: true

volumes:
  invoice_service_db_data:
    driver: local
    name: invoice_service_db_data